# This workflow will upload a Python Package using Twine when a release is created
# For more information see: https://help.github.com/en/actions/language-and-framework-guides/using-python-with-github-actions#publishing-to-package-registries

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Publish to test PyPi

on:
  push:
    branches:
      - "develop"
    tags:
      - "*"

permissions:
  contents: read

jobs:
  # test:
    # put test stuff here. see https://github.com/NREL/alfabet/blob/master/.github/workflows/run_tests_and_deploy.yml
  release:
    # needs: test
    if: startsWith(github.ref, 'refs/tags') #for publishing new tags
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ 3.8 ]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}

    - name: Get tag
      id: tag
      run: echo "::set-output name=version::${GITHUB_REF#refs/tags/}"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip setuptools wheel
        python -m pip install twine

    # Upload to TestPyPI
    - name: Build and Upload to TestPyPI
      run: python3 setup.py sdist bdist_wheel
    - name: Check the package
      run: twine check dist/*
    - name: Push to TestPyPI
      run: python3 -m twine upload dist/*
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.PYPI_TEST_TOKEN }}
        TWINE_REPOSITORY: testpypi

    - name: Create release notes
      if: success()
      run: |
        echo "Successfully published polyID ${{ steps.tag.outputs.version }} to TestPyPI" >> test_release_notes.txt

    - name: Upload release artifacts
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: testpypi-publish-logs-${{ github.run_id }}
        path: |
          test_release_notes.txt
          dist/
        retention-days: 30

    - name: Notify on failure
      if: failure()
      run: |
        echo "TestPyPI publish failed for version ${{ steps.tag.outputs.version }}" >> test_failure_log.txt
        echo "Check artifacts for detailed logs" >> test_failure_log.txt

    - name: Upload failure logs
      if: failure()
      uses: actions/upload-artifact@v3
      with:
        name: testpypi-publish-failure-${{ github.run_id }}
        path: test_failure_log.txt
        retention-days: 7